name: tldr_bot
channels:
 - defaults
dependencies:
 - python = 3.8.5
 - pip:
   - tensorflow == 2.4.0
   - numpy == 1.19.4
   - pandas == 1.1.5
   - scikit-learn == 0.24.0
   - flask == 1.1.2
   - matplotlib == 3.3.2
 
